### PR TITLE
Suggestion and Approval flags

### PR DESCRIPTION
**Pull request by johnsm21**
Users should be able to open an SDD in the SDD-Editor and approve ontology alignments by right-clicking on a cell and selecting "Approve". Non-approved cells show up with a yellow flag in the top right corner and when approved switch to a green flag. To make this more apparent the suggestion flag should be changed to Blue. Behind the scenes the editor should store who and what time the alignment was approved storing that information within the SDD itself so that the provenance is maintained within the file.

### CODE REVIEW

**Comment by johnsm21** [comment]
Is this ready for a formal review Aaron?

**Comment by johnsm21** [comment]
Are you addressing the other data dictionary bugs:
When adding to SDD the box to select which SDD to import is miss sized and hard to use
Back to SDD button doesn't work after adding to SDD doesn't work

**Comment by Aaron0372** [comment]
I believe what I have for the Approval flags is ready for a formal review. I can address the other Data Dictionary bugs in this branch or make a new one and address it there. I still need more time for the other DD bugs though.

**Comment by johnsm21** [comment]
I've been trying the new approval functionality and I don't think that it's working, When I right-click on the cell and select "Accept Value as Optimal Value", it doesn't give me a flag that it's approved. Also, that should probably just be "Approve"

**Comment by johnsm21** [comment]
Thanks, I can approve now! I did notice a bug and a few things that need to be changed. 

1. The column approval is based on the position of the cell. If I approve a cell and add a new row the approval transitions to a new position. It might be easier to just store what's been approved versus where the approval took place.

2. If someone changes an approved cell it should no longer be approved.

3. Please change the "Accept Value as Optimal Value" button to "Approve". Very rarely are these alignments optimal, even when humans do it, plus "Approve" is a bit more clear.

**Comment by johnsm21** [comment]
These changes address points 1 & 3, but when a user changes a cell it still doesn't remove the approval

**Comment by johnsm21** [comment]
This update addressed point 2. I did notice another bug, as rows are added or removed the cell suggestion flag doesn't "move" with the row. Could you take a look at that as well?

**Pull request merged**
